#include "MainWindow.h"
#include "ui_mainwindow.h" // This will be generated by Qt from mainwindow.ui
#include <QFileDialog>
#include <QStandardPaths>
#include <QDir>
#include <QMessageBox>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    // Note: The ui pointer will be fully initialized when Qt runs the MOC and UIC on mainwindow.ui
    ui->setupUi(this);

    // Initialize backend controllers
    QString appDataDir = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);
    QDir().mkpath(appDataDir);
    
    m_settingsManager = std::make_unique<SettingsManager>(appDataDir.toStdWString());
    m_payloadController = std::make_unique<PayloadController>();

    // Bind Core Callbacks to Qt UI Thread
    // We use a lambda to properly convert standard C++ types to Qt types
    m_payloadController->SetLogCallback([this](const std::wstring& msg) {
        // Enqueue call to main thread if not already on it
        QMetaObject::invokeMethod(this, "appendLogMessage", Qt::QueuedConnection, 
                                  Q_ARG(QString, QString::fromStdWString(msg)));
    });

    m_payloadController->SetStatusCallback([this](int status) {
        QMetaObject::invokeMethod(this, "updateDeviceStatus", Qt::QueuedConnection, 
                                  Q_ARG(int, status));
    });

    // Setup Timer to poll for RCM device
    m_statusTimer = new QTimer(this);
    connect(m_statusTimer, &QTimer::timeout, this, &MainWindow::checkRCMStatus);
    m_statusTimer->start(1000); // Check every second

    setupTrayIcon();
    loadSettings();
}

MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow::setupTrayIcon()
{
    m_trayIcon = new QSystemTrayIcon(this);
    // m_trayIcon->setIcon(QIcon(":/res/rcm_logo.png")); // Ensure resources are added
    
    m_trayIconMenu = new QMenu(this);
    QAction* showAction = new QAction("Show", this);
    QAction* exitAction = new QAction("Exit", this);
    
    connect(showAction, &QAction::triggered, this, &MainWindow::showNormal);
    connect(exitAction, &QAction::triggered, qApp, &QCoreApplication::quit);
    
    m_trayIconMenu->addAction(showAction);
    m_trayIconMenu->addSeparator();
    m_trayIconMenu->addAction(exitAction);
    
    m_trayIcon->setContextMenu(m_trayIconMenu);
    m_trayIcon->show();
}

void MainWindow::loadSettings()
{
    // Retrieve favorites testing
    auto favorites = m_settingsManager->GetFavorites();
    for (const auto& fav : favorites) {
        // ui->favoritesComboBox->addItem(QString::fromStdWString(fav));
    }
}

void MainWindow::checkRCMStatus()
{
    int rc = m_payloadController->GetRcmStatus();
    
    if (rc >= 0) {
        // RCM Detected
        // ui->statusLabel->setText("RCM Device Detected!");
        // ui->statusLabel->setStyleSheet("color: green;");
        // ui->btnInject->setEnabled(true);
    } else {
        // RCM Not Detected
        // ui->statusLabel->setText("NO RCM Device Detected");
        // ui->statusLabel->setStyleSheet("color: red;");
        // ui->btnInject->setEnabled(false);
    }
}

void MainWindow::on_btnBrowsePayload_clicked()
{
    QString fileName = QFileDialog::getOpenFileName(this, "Select Payload", "", "Bin Files (*.bin);;All Files (*)");
    if (!fileName.isEmpty()) {
        // ui->payloadPathLineEdit->setText(fileName);
    }
}

void MainWindow::on_btnInject_clicked()
{
    // QString payloadPath = ui->payloadPathLineEdit->text();
    QString payloadPath; // Placeholder mapping
    if (payloadPath.isEmpty()) {
        QMessageBox::warning(this, "Error", "Please select a payload file first.");
        return;
    }

    // Qt uses QtConcurrent or QThread for non-blocking. 
    // Wait for full Qt threading integration; for now we run it inline or spawn a process.
    m_payloadController->InjectPayload(payloadPath.toStdWString());
}

void MainWindow::appendLogMessage(const QString& message)
{
    // ui->logTextEdit->appendPlainText(message);
}

void MainWindow::updateDeviceStatus(int statusCode)
{
    if (statusCode == 0) {
        m_trayIcon->showMessage("Success", "Payload injected successfully!", QSystemTrayIcon::Information, 2000);
    } else {
        m_trayIcon->showMessage("Error", "Error injecting payload", QSystemTrayIcon::Critical, 2000);
    }
}
