#pragma once

#include <QMainWindow>
#include <QSystemTrayIcon>
#include <QMenu>
#include <QTimer>
#include <memory>
#include "PayloadController.h"
#include "SettingsManager.h"

// Forward declaration of UI namespace (generated by Qt from mainwindow.ui)
QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    // UI Slots
    void on_btnBrowsePayload_clicked();
    void on_btnInject_clicked();
    
    // Logic Slots (from Controller)
    void appendLogMessage(const QString& message);
    void updateDeviceStatus(int statusCode);
    void checkRCMStatus();

private:
    Ui::MainWindow *ui;
    
    std::unique_ptr<PayloadController> m_payloadController;
    std::unique_ptr<SettingsManager> m_settingsManager;

    QSystemTrayIcon* m_trayIcon;
    QMenu* m_trayIconMenu;
    QTimer* m_statusTimer;
    
    void setupTrayIcon();
    void loadSettings();
};
